name = "TrackingLoopFilters"
uuid = "0814aff9-93cb-554c-9fff-9bf1cfdb5efa"
authors = ["Erik Deinzer <erik.deinzer@rwth-aachen.de>", "Soeren Zorn <soeren.zorn@nav.rwth-aachen.de"]
version = "1.0.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Aqua = "0.8"
DocStringExtensions = "0.8, 0.9"
LinearAlgebra = "1"
Test = "1"
Unitful = "0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 1.0"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
